---
# tasks file for etc_hosts
- name: Ajout mappings vers  /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: "^{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias | regex_replace('-','_')]['ipv4']['address'] }}.*"
    line: "{{ hostvars[item]['ansible_'~hostvars[item].ansible_default_ipv4.alias | regex_replace('-','_')]['ipv4']['address'] }} {{ hostvars[item]['fqdn'] }}"
    insertafter: "^127..*$"
    state: present
  with_items:
    - "{{ groups['cluster']|sort(reverse=True) }}"