---
# tasks file for ambari-repo
  - name: Telechargement de Ambari repo 2.7
    get_url:
      url: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.0.0/ambari-2.7.0.0-centos7.tar.gz
      dest: /home/useradmin

  - name: Extraction
    unarchive:
      remote_src: yes
      src: /home/useradmin/ambari-2.7.0.0-centos7.tar.gz
      dest: /var/www/html