---
# tasks file for ambari-repo
  - name: Telechargement du repo HDP-3.0
    get_url:
      url: http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.0.0/HDP-3.0.0.0-centos7-rpm.tar.gz
      dest: /home/useradmin

  - name: Extraction du repo HDP-3.0
    unarchive:
      remote_src: yes
      src: /home/useradmin/HDP-3.0.0.0-centos7-rpm.tar.gz
      dest: /var/www/html



          